services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - CHROMA_DB_PATH=/workspace/chroma_db
    volumes:
      - ./chroma_db:/workspace/chroma_db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: always